#!/bin/bash
#
#	 Copyright (C) 2010		BENHAÏM Jérôme.
# 
# This file is part of GxInterface.
#
#    GxInterface is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    GxInterface is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with GxInterface.  If not, see <http://www.gnu.org/licenses/>.
#set -x
#generales
script_autor='BENHAÏM Jérôme'
script_ver='0.1'
script_released='01/04/2010'
script_name="syx2ins"
#
#messages
#
## Generale
msgacc="Bienvenue dans $script_name $script_ver de $script_autor réalisé le $script_released."
## Erreurs
msg_error_noparam="!!! Aucun parametre !!!"
msg_error_iter="!!! le parametre \"i\" attends un entier de 0 à 127(taille banque sons) pour determiner l'élèment de départ !!!"
msg_error_bank="!!! le parametre \"b\" attends un entier non nul de 1 à 127 pour determiner le nombre d'élèmentà extraire !!!"
msg_error_infile_inexist="!!! Fichier inexistant !!!"
## Aide
msg_help="Utilisation : syx2ins [OPTION]... fichier-d'entrée.syx... [fichier-de-sortie.ins]
OPTIONS : 
-b N designe le nombre d'élèments à extraire par defaut 128 (0 à 127) elements
-i N designe l'élèment de depart de l extraction par defaut à 0
$script_name nécéssite au minimum 1 parametre le fichier à lire.
Si un seul parametre est donné le fichier de sortie aura le même nom que le fichier d'entrée suivi de .ins
vous pouvez aussi specifier le nom du fichier de sortie apres le fichier d'entrée"

#taille de la banque de sons
banksize=127
#longeur de chaine en octet
width=32
#nombre d'octect non lu
skip=118
#nombre d'octet lu 
size=10
# iteration de depart
i=0

if [[ $# -eq 0 ]] ; then
	echo $msg_error_noparam
	echo $msg_help
	exit 1
fi
while getopts ":hb:i:" opts;do
		case $opts in
			#-h affiche l aide
			h) echo $msghelp
				exit 0;;	
			#specifie la taille de la banque
			b) if [[ $OPTARG == +([0-9]) && -n $OPTARG && $OPTARG -gt 0  ]] ;then
					banksize=$OPTARG-1
				else
					echo $msg_error_bank
					exit 1
				fi ;;
			#specifie l'iteration de depart
			i) if [[ $OPTARG == +([0-9]) && $OPTARG -ge 0 ]] ;then
					i=$OPTARG
				else
					echo $msg_error_iter
					exit 1
				fi ;;
			\?) echo $opts
			if [[ $opts == "-b" ]] ;then
					echo $msg_error_bank
				fi
				if [[ $opts == "-i" ]] ;then
					echo $msg_error_iter
				fi
				echo $msg_help
				exit 1 ;;
		esac
done
shift $(($OPTIND-1))
if [[ -f $1 && -r $1  ]] ;then
	if [[ -n $2 ]] ;then
		filename=$2
	else
		filename=${1%.*}
	fi
else
	echo $msg_error_infile_inexist
	echo $msg_help
	exit 1
fi
if [[ ! -f $filename.ins ]] ;then
	touch $filename.ins
	echo ";-----------------------------------------------------------------------

.Patch Names

" > $filename.ins
fi
bankname=${filename#*/}
echo "[DX7 $bankname]" >> $filename.ins
while [[ $i -le $banksize ]] ;do
	sk=$(($i*$size+$i*$skip+$skip))
	#echo "$i $skip : $sk "
	sound_name=`od -c -w$width -j$sk -N$size  $filename.syx`
	sound_name=`echo "$sound_name" | sed 's/^[0-9]*//g' | sed 's/[ ]\{3\}//g' | sed 's/ 177.*/<-->/g'`
	echo "$i=$i $sound_name" >> $filename.ins
	echo "instrument $i: $sound_name ecrit"
	((++i))
done
echo ".Instrument Definitions


[DX7 $bankname]
Patch[*]=DX7 $bankname
Control=Standard

;[DX7 $bankname Drums]
;Patch[*]=1..128
;Key[*,*]=DX7 $bankname Drums
;Drum[*,*]=1" >> $filename.ins

echo "$i instruments ecrit dans $filename.ins sous le nom de bank [DX7 $bankname]"

