#pragma once
#include <map>
#define ADD_ENUM(x) {static_cast<int>(snd_seq_event_type::x),#x}
static const std::map<int, std::string> enumMap = {
    ADD_ENUM(SND_SEQ_EVENT_SYSTEM),
    ADD_ENUM(SND_SEQ_EVENT_RESULT),

    ADD_ENUM(SND_SEQ_EVENT_NOTE),
    ADD_ENUM(SND_SEQ_EVENT_NOTEON),
    ADD_ENUM(SND_SEQ_EVENT_NOTEOFF),
    ADD_ENUM(SND_SEQ_EVENT_KEYPRESS),

    ADD_ENUM(SND_SEQ_EVENT_CONTROLLER),
    ADD_ENUM(SND_SEQ_EVENT_PGMCHANGE),
    ADD_ENUM(SND_SEQ_EVENT_CHANPRESS),
    ADD_ENUM(SND_SEQ_EVENT_PITCHBEND),
    ADD_ENUM(SND_SEQ_EVENT_CONTROL14),
    ADD_ENUM(SND_SEQ_EVENT_NONREGPARAM),
    ADD_ENUM(SND_SEQ_EVENT_REGPARAM),

    ADD_ENUM(SND_SEQ_EVENT_SONGPOS),
    ADD_ENUM(SND_SEQ_EVENT_SONGSEL),
    ADD_ENUM(SND_SEQ_EVENT_QFRAME),
    ADD_ENUM(SND_SEQ_EVENT_TIMESIGN),
    ADD_ENUM(SND_SEQ_EVENT_KEYSIGN),

    ADD_ENUM(SND_SEQ_EVENT_START),
    ADD_ENUM(SND_SEQ_EVENT_CONTINUE),
    ADD_ENUM(SND_SEQ_EVENT_STOP),
    ADD_ENUM(SND_SEQ_EVENT_SETPOS_TICK),
    ADD_ENUM(SND_SEQ_EVENT_SETPOS_TIME),
    ADD_ENUM(SND_SEQ_EVENT_TEMPO),
    ADD_ENUM(SND_SEQ_EVENT_CLOCK),
    ADD_ENUM(SND_SEQ_EVENT_TICK),
    ADD_ENUM(SND_SEQ_EVENT_QUEUE_SKEW),
    ADD_ENUM(SND_SEQ_EVENT_SYNC_POS),

    ADD_ENUM(SND_SEQ_EVENT_TUNE_REQUEST),
    ADD_ENUM(SND_SEQ_EVENT_RESET),
    ADD_ENUM(SND_SEQ_EVENT_SENSING),

    ADD_ENUM(SND_SEQ_EVENT_ECHO),
    ADD_ENUM(SND_SEQ_EVENT_OSS),

    ADD_ENUM(SND_SEQ_EVENT_CLIENT_START),
    ADD_ENUM(SND_SEQ_EVENT_CLIENT_EXIT),
    ADD_ENUM(SND_SEQ_EVENT_CLIENT_CHANGE),
    ADD_ENUM(SND_SEQ_EVENT_PORT_START),
    ADD_ENUM(SND_SEQ_EVENT_PORT_EXIT),
    ADD_ENUM(SND_SEQ_EVENT_PORT_CHANGE),

    ADD_ENUM(SND_SEQ_EVENT_PORT_SUBSCRIBED),
    ADD_ENUM(SND_SEQ_EVENT_PORT_UNSUBSCRIBED),

    ADD_ENUM(SND_SEQ_EVENT_USR0),
    ADD_ENUM(SND_SEQ_EVENT_USR1),
    ADD_ENUM(SND_SEQ_EVENT_USR2),
    ADD_ENUM(SND_SEQ_EVENT_USR3),
    ADD_ENUM(SND_SEQ_EVENT_USR4),
    ADD_ENUM(SND_SEQ_EVENT_USR5),
    ADD_ENUM(SND_SEQ_EVENT_USR6),
    ADD_ENUM(SND_SEQ_EVENT_USR7),
    ADD_ENUM(SND_SEQ_EVENT_USR8),
    ADD_ENUM(SND_SEQ_EVENT_USR9),

    ADD_ENUM(SND_SEQ_EVENT_SYSEX),
    ADD_ENUM(SND_SEQ_EVENT_BOUNCE),
    ADD_ENUM(SND_SEQ_EVENT_USR_VAR0),
    ADD_ENUM(SND_SEQ_EVENT_USR_VAR1),
    ADD_ENUM(SND_SEQ_EVENT_USR_VAR2),
    ADD_ENUM(SND_SEQ_EVENT_USR_VAR3),
    ADD_ENUM(SND_SEQ_EVENT_USR_VAR4),

    ADD_ENUM(SND_SEQ_EVENT_NONE),
};
