po_DATA = \
	ChangeLog\
	de.po \
	en.po \
	es.po \
	fr.po \
	jap.po \
	ru.po 

podir = \
	$(pkgdatadir)/po

EXTRA_DIST = \
	$(po_DATA)\
	$(PACKAGE_NAME).pot \
	languagecode.po \
	LINGUAS \
	Makefile.am \
	Makefile.in.in \
	missing \
	notexist \
	POTFILES \
	POTFILES.in \
	POTFILES.skip

## File created by the gnome-build tools
