image_DATA = \
	S_HOLD.png\
	TRI.png\
	SQU.png\
	SIN.png\
	SAW-.png\
	SAW+.png\
	algo1.png\
	algo2.png\
	algo3.png\
	algo4.png\
	algo5.png\
	algo6.png\
	algo7.png\
	algo8.png\
	algo9.png\
	algo10.png\
	algo11.png\
	algo12.png\
	algo13.png\
	algo14.png\
	algo15.png\
	algo16.png\
	algo17.png\
	algo18.png\
	algo19.png\
	algo20.png\
	algo21.png\
	algo22.png\
	algo23.png\
	algo24.png\
	algo25.png\
	algo26.png\
	algo27.png\
	algo28.png\
	algo29.png\
	algo30.png\
	algo31.png\
	algo32.png\
	dx7.jpg\
	keyboard.png\
	keyboard_background.png\
	touche_b.png\
	touche_w.png


imagedir = \
	$(pkgdatadir)/$(PACKAGE_VERSION)/images

## File created by the gnome-build tools

