#! /bin/bash
#
#	 Copyright (C) 2024		BENHAÏM Jérôme.
# 
# This file is part of GxInterface.
#
#    GxInterface is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    GxInterface is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with GxInterface.  If not, see <http://www.gnu.org/licenses/>.

### ARCHLINUX like
# using PKGBUILD ( get the PKBUILD from source directory
# 	of the package(gxinterface, dx7interface) you want to build )
cp PKGBUILD /to/your/build/directory
cd /to/your/build/directory
makepkg -si 

## Manually
echo "
Installer les outils de compilation ( makepkg )
    les autotool (autoconf automake autogen autotools-dev)
    les outils de traduction (libtool gettext)
    les libraries c++ gtk (libgtkmm-3.0-dev )
    la librairie alsa (libasound2-dev)
    l'outils de build du paquets deb (checkinstall)
"

common="autoconf autogen automake libtool gettext base-devel m4"
libdev="glibmm gtkmm3 cairomm-1.16 alsa-lib intltool"

distrib=$(grep DISTRIB_ID /etc/lsb-release | sed 's/.*="\(.*\)"/\1/' )
Arch="makepkg devtools"
ManjaroLinux="manjaro-tools-base manjaro-tools-pkg"

sudo pacman -Syu ${common} ${!distrib} ${libdev}
#pacman -Rdd breezy intltool autoconf autogen automake libtool

echo "Enlever l'ancien gxinterface
    nettoyer les repertoire des sources (make distclean et make clean)
    lancer la generation par les autotools (autogen.sh)
    lance implicitement la configuration (configure)
    lancer le build (make)
    et lancer checkinstall avec le numero de version 1.0.0
"

cd ../../gxinterface
sudo pacman -R gxinterface
make clean ; make distclean
./autogen.sh --prefix=/usr --disable-maintainer-mode
make -j3

echo "Enlever l'ancien dx7interface
    nettoyer les repertoire des sources (make distclean ou make clean)
    lancer la generation par les autotols (autogen.sh)
    lancer la configuration (configure)
    lancer le build (make)
    et lancer checkinstall avec le numero de version 1.0.0
    ## make distclean || make clean && NOCONFIGURE=no  ./autogen.sh --prefix=/usr && sudo checkinstall -D --fstrans=no --install=yes --pkgversion="1.0.0" -y 
"
cd ../dx7interface
make clean ; make distclean
./autogen.sh --prefix=/usr --disable-maintainer-mode
make -j3

